- name: 安装nginx
  apt: name=nginx state=present

# 解决访问dss报403的问题
- name: 配置nginx
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: '^user'
    line: 'user root;'

- name: 启动nginx服务
  systemd: name=nginx enabled=yes daemon_reload=yes state=restarted
  tags:
    - restart

- name: 创建/opt/ansible-role-datasphere/目录
  file:
    path: /var/www/html
    state: directory

- name: 更新首页信息
  template:
    src: "index.html.j2"
    dest: "/usr/share/nginx/html/index.html"

- name: 添加repo
  become: true
  template:
    src: "repo.conf.j2"
    dest: /etc/nginx/conf.d/repo.conf

- name: 重载nginx配置
  become: true
  command: "nginx -s reload"

- name: 测试访问nginx
  uri:
    url: http://127.0.0.1
    return_content: yes
    status_code: 200
  register: curl_info

- name: 打印请求信息
  debug: var=curl_info.msg
