---
- name: 创建/opt/ansible-role-datasphere/目录
  file:
    path: /opt/ansible-role-datasphere
    state: directory

- name: 解压 ambari hdp软件
  shell:
    cmd: "{{ item }}"
  with_items:
    - tar -zxvf /mnt/cloudera-Ambari-2.7.5.0-Hadoop-3.1.5-ubuntu18/ambari-2.7.5.0-ubuntu18.tar.gz -C /var/www/html/
    - tar -zxvf /mnt/cloudera-Ambari-2.7.5.0-Hadoop-3.1.5-ubuntu18/HDP-3.1.5.0-ubuntu18-deb.tar.gz -C /var/www/html/
    - tar -zxvf /mnt/cloudera-Ambari-2.7.5.0-Hadoop-3.1.5-ubuntu18/HDP-UTILS-1.1.0.22-ubuntu18.tar.gz -C /var/www/html/
    - tar -zxvf /mnt/cloudera-Ambari-2.7.5.0-Hadoop-3.1.5-ubuntu18/HDP-GPL-3.1.5.0-ubuntu18-gpl.tar.gz -C /var/www/html/

- name: 添加hdp apt认证文件
  copy:
    src: trusted.gpg
    dest: /etc/apt/trusted.gpg.d/trusted.gpg

- name: 配置环境变量
  lineinfile:
    dest: /etc/apt/sources.list.d/ambari.list
    state: present
    create: yes
    line: "deb [trusted=yes] http://{{ ansible_ssh_host }}:{{AMBARI_REPO_PORT}}/ambari/ubuntu18/2.7.5.0-72/ Ambari main"

- name: 安装ambari-server
  shell:
    cmd: apt-get update && apt-get install -y ambari-server ambari-agent

- name: 修改metainfo.xml文件，禁用SMARTSENSE组件
  lineinfile:
    dest:  /var/lib/ambari-server/resources/stacks/HDP/3.0/services/SMARTSENSE/metainfo.xml
    state: absent
    regexp: '.*<selection>MANDATORY</selection>.*'

- name: 拷贝mysql-connector-java-8.0.30.jar
  copy:
    src: mysql-connector-java-8.0.30.jar
    dest: /usr/share/java/

- name: 创建ambari数据库
  command:  mysql --login-path=local -e "{{ item }}"
  with_items:
    - CREATE DATABASE ambari;

- name: 初始化ambari数据库
  command:  mysql --login-path=local --database=ambari -e "{{ item }}"
  with_items:
    - source /opt/ansible-role-datasphere/roles/ambari/files/Ambari-DDL-MySQL-CREATE.sql;

- name: hive数据库连接器
  copy:
    src: mysql-connector-java-8.0.30.jar
    dest: /var/lib/ambari-server/resources/mysql-connector-java-8.0.30.jar/

- name: 创建ambari数据库
  command:  mysql --login-path=local -e "{{ item }}"
  with_items:
    - CREATE DATABASE hive;

- name: 初始化ambari数据库
  command:  mysql --login-path=local --database=hive -e "{{ item }}"
  with_items:
    - source /opt/ansible-role-datasphere/roles/ambari/files/hive-schema-3.1.1000.mysql.sql;

- name: 添加ambari password.dat文件
  template: src=password.dat.j2 dest=/etc/ambari-server/conf/password.dat owner=root

- name: 添加ambari ambari.properties文件
  template: src=ambari.properties.j2 dest=/etc/ambari-server/conf/ambari.properties owner=root

- name: #配置重启ambari-server脚本
  shell:
    cmd: ambari-server restart

- name: 打印访问信息
  debug:
    msg:
      - "*****************************************************************"
      - "             访问 http://{{ ansible_ssh_host }}:8080 查看访问信息               "
      - "*****************************************************************"